### ISSUE TITLE
Unable to run EF5 command in linux - "ERROR:src/BasicGrids.cpp(73): Failed to load DEM!"

### ISSUE THREAD

**Issue by bhanu-magotra** [HyDROSLab/EF5#27]
Hi, 
I tried running EF5 through terminal in example directory of training data set and I encountered following error:
ERROR:src/BasicGrids.cpp(73): Failed to load DEM!
How do I resolve this?
![image](https://user-images.githubusercontent.com/60338532/73248925-daa24e00-41d9-11ea-938b-c2f6a70b4832.png)

**Comment by YiChaoA** [comment]
i also have this problem...
i guess this is because our pixel type and pixel depth of DEM is not floating point and 32bit... so get this error
