### ISSUE TITLE
PET data units are not matching in examples given in the short course training package, which is available on the EF5 website.

### ISSUE THREAD

**Issue by saikirankuntla** [HyDROSLab/EF5#28]
I downloaded the short course training package available on the EF5 website(http://ef5.ou.edu/training/).  I worked on the example basins, which are the Wangchu basin and example2. I found that, though both examples are using the same PET data(FEWSNET). The PET values have different units in the control file. The Wangchu basin has mm/d, whereas example2 has mm/h. May I know the reason for the same.
The control files of both the basins are attached to this post for your kind reference. 
[control.txt](https://github.com/HyDROSLab/EF5/files/4212843/control.txt)
[control.txt](https://github.com/HyDROSLab/EF5/files/4212847/control.txt)

**Comment by zflamig** [comment]
Just a mistake, probably the correct units are mm/d. If you are using CREST and calibrating it doesn't matter much because there is a parameter which adjusts PET anyways.

**Comment by saikirankuntla** [comment]
Thanks for the confirmation, and I appreciate the quick response.
