### ISSUE TITLE
Observerd values are not being displayed in the final output given by EF5 model.

### ISSUE THREAD

**Issue by saikirankuntla** [HyDROSLab/EF5#29]
I tried to run the EF5 model using all the required files. The model ran successfully, and I got the output file with discharge values. But the output excel file was not showing the observed values in it. Though I tried with all the formats of dates in the observed file, which are accepted by EF5(as shown in the training video in the EF5 website), I was unsuccessful. But when I tried with the observed values of the example2 basin(whose date format is not according to the prescribed format) available in the short course training package, observed values were seen in my output excel file for my study area. May I know the reason for the same. 
I also observed that the format of dates in the output file is changing for every ten dates. why is it so?
I am attaching the images of the observed data of example2, sample observed data of my study area and the output file for your kind reference.
![example2_observed](https://user-images.githubusercontent.com/61139988/74645388-d8f6f500-519d-11ea-94f0-f02fd8490474.PNG)
![observed_input](https://user-images.githubusercontent.com/61139988/74645395-dac0b880-519d-11ea-9359-f657619351a6.PNG)
![output](https://user-images.githubusercontent.com/61139988/74645396-dac0b880-519d-11ea-9339-8636bec752da.PNG)

**Comment by msaharia** [comment]
Hi @zflamig - Sai is my PhD student. And we ran into this issue as he has described. Somehow the observed data is not being read correctly. And also, the date format seems to fluctuate. Would appreciate any help!

**Comment by zflamig** [comment]
Excel is parsing some of your dates, probably you are using a locale that uses dd/mm/yyyy notation. EF5 supports either mm/dd/yyyy or yyyy/mm/dd format. So reformat your observation times to be yyyy/mm/dd hh:mm and it should work.
